
CREATE TABLE [dbo].[bodacc] (

#pas Optimisée pour recrutement

[id] INT  IDENTITY (1, 1) NOT NULL,
[siren] VARCHAR (MAX) NULL,
[nic] VARCHAR (MAX) NULL,
[siret] VARCHAR (MAX) NULL,
[statutDiffusionEtablissement] VARCHAR (MAX) NULL,
[dateCreationEtablissement] VARCHAR (MAX) NULL,
[trancheEffectifsEtablissement] VARCHAR (MAX) NULL,
[anneeEffectifsEtablissement] VARCHAR (MAX) NULL,
[activitePrincipaleRegistreMetiersEtablissement] VARCHAR (MAX) NULL,
[dateDernierTraitementEtablissement] VARCHAR (MAX) NULL,
[etablissementSiege] VARCHAR (MAX) NULL,
[nombrePeriodesEtablissement] VARCHAR (MAX) NULL,
[complementAdresseEtablissement] VARCHAR (MAX) NULL,
[numeroVoieEtablissement] VARCHAR (7) NULL,
[indiceRepetitionEtablissement] VARCHAR (MAX) NULL,
[dernierNumeroVoieEtablissement] VARCHAR (7) NULL,
[indiceRepetitionDernierNumeroVoieEtablissement] VARCHAR (MAX) NULL,
[typeVoieEtablissement] VARCHAR (7) NULL,
[libelleVoieEtablissement] VARCHAR (MAX) NULL,
[codePostalEtablissement] VARCHAR (5) NULL,
[libelleCommuneEtablissement] VARCHAR (MAX) NULL,
[libelleCommuneEtrangerEtablissement] VARCHAR (MAX) NULL,
[distributionSpecialeEtablissement] VARCHAR (MAX) NULL,
[codeCommuneEtablissement] VARCHAR (MAX) NULL,
[codeCedexEtablissement] VARCHAR (5) NULL,
[libelleCedexEtablissement] VARCHAR (MAX) NULL,
[codePaysEtrangerEtablissement] VARCHAR (MAX) NULL,
[libellePaysEtrangerEtablissement] VARCHAR (MAX) NULL,
[identifiantAdresseEtablissement] VARCHAR (MAX) NULL,
[coordonneeLambertAbscisseEtablissement] VARCHAR (MAX) NULL,
[coordonneeLambertOrdonneeEtablissement] VARCHAR (MAX) NULL,
[complementAdresse2Etablissement] VARCHAR (MAX) NULL,
[numeroVoie2Etablissement] VARCHAR (6) NULL,
[indiceRepetition2Etablissement] VARCHAR (MAX) NULL,
[typeVoie2Etablissement] VARCHAR (MAX) NULL,
[libelleVoie2Etablissement] VARCHAR (MAX) NULL,
[codePostal2Etablissement] VARCHAR (5) NULL,
[libelleCommune2Etablissement] VARCHAR (MAX) NULL,
[libelleCommuneEtranger2Etablissement] VARCHAR (MAX) NULL,
[distributionSpeciale2Etablissement] VARCHAR (MAX) NULL,
[codeCommune2Etablissement] VARCHAR (5) NULL,
[codeCedex2Etablissement] VARCHAR (MAX) NULL,
[libelleCedex2Etablissement] VARCHAR (MAX) NULL,
[codePaysEtranger2Etablissement] VARCHAR (MAX) NULL,
[libellePaysEtranger2Etablissement] VARCHAR (MAX) NULL,
[dateDebut] VARCHAR (MAX) NULL,
[etatAdministratifEtablissement] VARCHAR (MAX) NULL,
[enseigne1Etablissement] VARCHAR (MAX) NULL,
[enseigne2Etablissement] VARCHAR (MAX) NULL,
[enseigne3Etablissement] VARCHAR (MAX) NULL,
[denominationUsuelleEtablissement] VARCHAR (MAX) NULL,
[activitePrincipaleEtablissement] VARCHAR (MAX) NULL,
[nomenclatureActivitePrincipaleEtablissement] VARCHAR (MAX) NULL,
[caractereEmployeurEtablissement]
);
